version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lux-explorer-frontend
    restart: unless-stopped
    environment:
      # Network configuration
      NEXT_PUBLIC_NETWORK_NAME: LUX Network
      NEXT_PUBLIC_NETWORK_SHORT_NAME: LUX
      NEXT_PUBLIC_NETWORK_ID: 96369
      NEXT_PUBLIC_NETWORK_CURRENCY_NAME: LUX
      NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL: LUX
      NEXT_PUBLIC_NETWORK_CURRENCY_DECIMALS: 18
      
      # Branding
      NEXT_PUBLIC_NETWORK_LOGO: https://lux.network/images/6334ed6d2918e27358af1001_lux-logo-upside-down-triangle-p-800_1-p-500.png
      NEXT_PUBLIC_NETWORK_LOGO_DARK: https://lux.network/images/6334ed6d2918e27358af1001_lux-logo-upside-down-triangle-p-800_1-p-500.png
      NEXT_PUBLIC_NETWORK_ICON: https://lux.network/images/6334ed6d2918e27358af1001_lux-logo-upside-down-triangle-p-800_1-p-500.png
      NEXT_PUBLIC_NETWORK_ICON_DARK: https://lux.network/images/6334ed6d2918e27358af1001_lux-logo-upside-down-triangle-p-800_1-p-500.png
      NEXT_PUBLIC_OG_IMAGE_URL: https://lux.network/images/6334ed6d2918e27358af1001_lux-logo-upside-down-triangle-p-800_1-p-500.png
      
      # Font configuration
      NEXT_PUBLIC_FONT_FAMILY_HEADING: '{"name": "Inter", "url": "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"}'
      NEXT_PUBLIC_FONT_FAMILY_BODY: '{"name": "Inter", "url": "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"}'
      
      # Theme configuration
      NEXT_PUBLIC_COLOR_THEME_DEFAULT: dark
      NEXT_PUBLIC_HOMEPAGE_PLATE_BACKGROUND: black
      NEXT_PUBLIC_HOMEPAGE_PLATE_TEXT_COLOR: white
      
      # API configuration
      NEXT_PUBLIC_API_HOST: lux-explorer-backend
      NEXT_PUBLIC_API_BASE_PATH: /
      NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL: ws
      
      # Network dropdown (all LUX ecosystem networks)
      NEXT_PUBLIC_FEATURED_NETWORKS: /networks.json
      
      # Other configurations
      NEXT_PUBLIC_IS_ACCOUNT_SUPPORTED: 'true'
      NEXT_PUBLIC_AUTH_URL: http://lux-explorer-backend:4000
      NEXT_PUBLIC_LOGOUT_URL: https://luxwallet.xyz/api/auth/logout
      NEXT_PUBLIC_STATS_API_HOST: http://lux-explorer-stats:8050
      NEXT_PUBLIC_VISUALIZE_API_HOST: http://lux-explorer-visualizer:8050
      NEXT_PUBLIC_CONTRACT_INFO_API_HOST: http://lux-explorer-backend:4000
      NEXT_PUBLIC_ADMIN_SERVICE_API_HOST: http://lux-explorer-backend:4000
      
    networks:
      - explorer-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lux-explorer.rule=Host(`explore.lux.network`)"
      - "traefik.http.routers.lux-explorer.entrypoints=websecure"
      - "traefik.http.routers.lux-explorer.tls.certresolver=letsencrypt"
      - "traefik.http.services.lux-explorer.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik"
    volumes:
      - ./public/networks.json:/app/public/networks.json:ro
      - ./public/favicon.ico:/app/public/favicon.ico:ro

networks:
  explorer-network:
    external: true
  traefik:
    external: true