version: '3.8'

services:
  frontend:
    image: ghcr.io/blockscout/frontend:latest
    container_name: lux-explorer-frontend
    restart: unless-stopped
    ports:
      - "3100:3000"
    environment:
      # Network configuration
      NEXT_PUBLIC_NETWORK_NAME: LUX Network
      NEXT_PUBLIC_NETWORK_SHORT_NAME: LUX
      NEXT_PUBLIC_NETWORK_ID: 96369
      NEXT_PUBLIC_NETWORK_CURRENCY_NAME: LUX
      NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL: LUX
      NEXT_PUBLIC_NETWORK_CURRENCY_DECIMALS: 18
      
      # Branding
      NEXT_PUBLIC_NETWORK_LOGO: /logos/lux-logo-white.png
      NEXT_PUBLIC_NETWORK_LOGO_DARK: /logos/lux-logo-white.png
      NEXT_PUBLIC_NETWORK_ICON: /logos/lux-logo-white.png
      NEXT_PUBLIC_NETWORK_ICON_DARK: /logos/lux-logo-white.png
      NEXT_PUBLIC_OG_IMAGE_URL: /logos/lux-logo-white.png
      
      # Font configuration
      NEXT_PUBLIC_FONT_FAMILY_HEADING: '{"name": "Inter", "url": "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"}'
      NEXT_PUBLIC_FONT_FAMILY_BODY: '{"name": "Inter", "url": "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"}'
      
      # Theme configuration
      NEXT_PUBLIC_COLOR_THEME_DEFAULT: dark
      NEXT_PUBLIC_HOMEPAGE_PLATE_BACKGROUND: black
      NEXT_PUBLIC_HOMEPAGE_PLATE_TEXT_COLOR: white
      
      # API configuration
      NEXT_PUBLIC_API_HOST: api-explore.lux.network
      NEXT_PUBLIC_API_PROTOCOL: https
      NEXT_PUBLIC_API_BASE_PATH: /
      NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL: wss
      
      # Network dropdown (all LUX ecosystem networks)
      NEXT_PUBLIC_FEATURED_NETWORKS: '[]'
      
      # App host
      NEXT_PUBLIC_APP_HOST: explore.lux.network
      NEXT_PUBLIC_APP_PROTOCOL: https
      
      # Other configurations
      NEXT_PUBLIC_IS_ACCOUNT_SUPPORTED: 'true'
      NEXT_PUBLIC_AUTH_URL: https://api-explore.lux.network
      NEXT_PUBLIC_LOGOUT_URL: https://luxwallet.xyz/api/auth/logout
      NEXT_PUBLIC_STATS_API_HOST: https://api-explore.lux.network/api/stats
      NEXT_PUBLIC_VISUALIZE_API_HOST: https://api-explore.lux.network/api/visualize
      NEXT_PUBLIC_CONTRACT_INFO_API_HOST: https://api-explore.lux.network
      NEXT_PUBLIC_ADMIN_SERVICE_API_HOST: https://api-explore.lux.network
      
    networks:
      - hanzo-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lux-explorer.rule=Host(`explore.lux.network`)"
      - "traefik.http.routers.lux-explorer.entrypoints=websecure"
      - "traefik.http.routers.lux-explorer.tls.certresolver=letsencrypt"
      - "traefik.http.services.lux-explorer.loadbalancer.server.port=3000"
      - "traefik.docker.network=hanzo-network"
    volumes:
      - /home/z/logos:/app/public/logos:ro

networks:
  hanzo-network:
    external: true